config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'
  get '/authenticate', to: 'albums#authenticate'
  get '/callback', to: 'albums#callback'
  devise_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_filter do
    @discogs = Discogs::Wrapper.new("Vinyl Buddy", session[:access_token])
  end

  def index
    if params_exist?(params)
      @artist = params["artist"]
      @album = params["album"]

      get_data(@artist, @album)
    end
  end

  # Add an action to initiate the process.
  def authenticate
    request_data = @discogs.get_request_token("ENV[token]", "ENV[secret]", "http://127.0.0.1:3000/callback")
    session[:request_token] = request_data[:request_token]
    redirect_to request_data[:authorize_url]
  end

  # And an action that Discogs will redirect back to.
  def callback
    request_token = session[:request_token]
    verifier      = params[:oauth_verifier]
    access_token  = @discogs.authenticate(request_token, verifier)

    session[:request_token] = nil
    session[:access_token]  = access_token

    @discogs.access_token = access_token
    redirect_to :action => "index"


    # You can now perform authenticated requests.
  end


  def params_exist?(params)
    params["artist"] == nil ? false : true
  end

  def get_data(artist, album)

    wrapper = Discogs::Wrapper.new("Vinyl Buddy", user_token: ENV['DISCOGS_USER_TOKEN'])

    discogs_search = wrapper.search("#{@artist} - #{@album}")
    vinyl = []


    discogs_search.results.each do |album|
      unless album.format.nil?
        vinyl << album if album.format[0] == "Vinyl"
      end
    end

    if vinyl[0].type == "release"
      release = vinyl[0].id
    else
      release = vinyl[1].id
    end

    agent = Mechanize.new do |a|
      a.user_agent_alias = 'Mac Safari'
    end


    # Find discogs price
    login_page = agent.get "http://www.discogs.com/sell/history/#{release}"


    username_form = login_page.forms[0].field_with(name: "username")
    password_form = login_page.forms[0].field_with(name: "password")

    username_form.value = ENV['DISCOGS_USER_NAME']
    password_form.value = ENV['DISCOGS_PASSWORD']

    agent.submit(login_page.forms[0], login_page.forms[0].buttons.first)

    price_data = agent.page.css('div.clearfix li')

    @price_data = price_data[1].text[21 .. 26]

    # Find allmusic album rating
    agent.get "http://www.allmusic.com/search/albums/#{@artist}+#{@album}"

    
    # agent.page.link_with(text: "#{album}").click <-- this only works if cases are exactly perfect
    album_link = "http://www.allmusic.com" + agent.page.css("li.album")[0].children.children[1].attributes["href"].value
    agent.get(album_link)
    rating_div = agent.page.search('div.allmusic-rating')
    @album_rating = rating_div[0].children.text.strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/views/albums/index.html.erb
<div class="container">
  <div class="form row">
    <div class="small-6 small-centered columns">
      <form action="/" method="get">
        Artist:<br>
        <input type="text" name="artist"><br>
        Album:<br>
        <input type="text" name="album">
        <div class="row">
          <div class="small-5 small-centered column">
            <button class="button large">Get Album Info*</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="results-container">
    <p class="artist"><%= @artist %> <%= @album %></p>
    <span class="extra-info">Album Rating: </span><span class="answer"><%=@album_rating %></span> <br>
    <span class="extra-info">Average Price: </span><span class="answer"><%=@price_data %></span>
    <p>*Make sure you spell the artist and album name correctly, it won't work if you don't.</p>
  </div>

  <%= link_to 'Authenticate', authenticate_path, method: :get, class: :button %>
  
</div>

app/views/homes/index.html.erb
<div class="form row">
  <div class="small-6 columns">
    <form action="/" method="get">
      Artist:<br>
      <input type="text" name="artist"><br>
      Album:<br>
      <input type="text" name="album">

      <br> <button class="button">Submit</button>
    </form>
  </div>
</div>

<%= @album_rating %>

<%= @price_data %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VinylBuddy2</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>